version: '3'

services:
  app:
    container_name: bot
    build: .
    command: python /code/app/main.py
    working_dir: /code/app
    env_file:
      - .env
    restart: always
    volumes:
      - .:/code